name: tourism_currency_converter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.2+2
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.1.0
  url_launcher: ^6.3.1
  geolocator: ^14.0.1
  geocoding: ^4.0.0
  google_fonts: ^6.2.1
  simple_animations: ^5.2.0
  flutter_animate: ^4.5.2
  webview_flutter: ^4.13.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.13.1"
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/flags/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.png"
